== jpstrack.android

The widely-used version of JPSTrack, as found on Android devices everywhere.

JPSTrack is a map-making tool for OpenStreetMap.

=== You don't want the source

Look, if you just want to run this app, go and
link:$$https://play.google.com/store/apps/details?id=jpstrack.android$$[get it for free
from Google's Play Store].
Just because it's "open source" does *not* mean you have to build it from source to use it!

=== Build Pre-req

You must have the AppCompatv7 library project installed to build with Eclipse.

Note that building under Eclipse currently builds an APK missing some main .class files :-(

=== HowTo Build

Finally, before you can build this from source, you must copy one sample file, in res/raw.
Directions are contained in the sample file in that directory.

Once that's done, it should compile under either Eclipse or Maven,
assuming you have the Android SDK installed.

Oh, for now, the Eclipse classpath is not Mavenized, so create an
Eclipse classpath variable M2_REPO set to $HOME/.m2/repository,
and extend it to darwinsys-api-1.0.3.jar
Better yet, Mavenize the Eclipse classpath and send me a pull request.
