== JpsTrack Privacy Policy

=== Summary

JpsTrack will never capture identifiable information about you without
your consent. This app does not communicate with our servers at all,
except to view static HTML pages. The app obviously captures your
location information, as that is the intent of the application. "By
using the JpsTrack application, you consent to storing your location
information. By using the Upload feature, you consent to your location
information being transmitted to OpenStreetMap.org (OSM), where their
privacy policy applies. You consented to this policy when you created
your OpenStreetMap account."

=== Data Details

Note that the mobile application saves some of this data onto your
device, but we do not capture ANY of it to our web service. We do save
your OpenStreetMap account name onto your device. We do not save your
OSM password, out of an abundance of caution. The application is open
source so you can verify this yourself, by looking at
https://github.com/IanDarwin/jpstrack.android[the github repo.]

The only time we upload identifiable stuff is to OpenStreetMap. In that
case, you are covered by OpenStreetMap's own privacy policy, which we
have no control over and which you must have consented to when creating
your OSM account.

=== Permissions Used

Here is a list of the permissions we ask Android for, and why we ask for
each one:

[cols=",",options="header",]
|===
|Perm |Why
|ACCESS_COARSE_LOCATION |To find out where you are.

|ACCESS_FINE_LOCATION |To find out where you are.

|WRITE_EXTERNAL_STORAGE |To save notes and photos to your SD card or
storage.

|RECORD_AUDIO |To let you take voice notes.

|PERSISTENT_ACTIVITY |To keep the program running while mapping.

|INTERNET |To upload data to openstreetmap's database, only if you
provide an account and password, and for uploading anonymous crash
reporting info.
|===

=== Contact

If you need to contact us, please email jpstrack-feedback@darwinsys.com.

Thank you for using JpsTrack!
